### ISSUE TITLE
Slider is hidden by UITableViewCell, when cell height is to small

### ISSUE THREAD

**Issue by Ma-He** [alskipp/ASValueTrackingSlider#1]
![asvalueslider hidden by uitableviewcell](https://cloud.githubusercontent.com/assets/2759408/2613595/7839b532-bbd9-11e3-9664-afee3ff74587.png)
Is there any chance to bring the popup view in front of all other views?

**Comment by vitaliypriydun** [comment]
It can happen if you are calling [tableview reloadData] after changing slider value like I did.
So I haven`t found a way to dodge this and moved it from valueChanged to didFinishEditing
