### ISSUE TITLE
Slider not changing between colors when changing value

### ISSUE THREAD

**Issue by AJ1310** [alskipp/ASValueTrackingSlider#20]
self.recordPercentageSlider = [ASValueTrackingSlider new];
  self.recordPercentageSlider.delegate = self;
  self.recordPercentageSlider.frame = CGRectMake(20.0, 45.0, CGRectGetWidth(self.frame) - 2.0 * 20.0, 31.0);
  //self.recordPercentageSlider.value = 1.0;
  self.recordPercentageSlider.font = [UIFont fontWithName:@"AvenirNext-Medium" size:15.0];
  self.recordPercentageSlider.tintColor = [UIColor autumnColorWithAlpha:ZTAlphaLevelFull];
  [self.recordPercentageSlider addTarget:self action:@selector(recordPercentageValueChanged) forControlEvents:UIControlEventValueChanged];
  [self.contentView addSubview:self.recordPercentageSlider];
  
  NSNumberFormatter *numberFormatter = [[NSNumberFormatter alloc] init];
  [numberFormatter setNumberStyle:NSNumberFormatterPercentStyle];
  [self.recordPercentageSlider setNumberFormatter:numberFormatter];
  self.recordPercentageSlider.popUpViewAnimatedColors = @[[UIColor carbonColorWithAlpha:ZTAlphaLevelFull], [UIColor autumnColorWithAlpha:ZTAlphaLevelFull]];

This is the code I used for inserting the slider but will only display the first color in the array. I used these same lines for two different part of a project, both in table's cells, in which the animation did trigger while the other didn't.

**Comment by alskipp** [comment]
These issues seem to have been resolved when using the latest Xcode release (6.3). I'll close the issue for now on the assumption that all is well **crossed fingers**.
