### ISSUE TITLE
Issue when sliding from a long string to a shorter one

### ISSUE THREAD

**Issue by Deub27** [alskipp/ASValueTrackingSlider#24]
When using custom strings with different lengths in popUpView label, if you slide from a long string to a shorter string, the long string remains appearing a bit while target popupview size is already drawn.
It can be seen in your demo project.

**Comment by alskipp** [comment]
Many moons later…

The default is now to not animate the text (currently in development branch - will be merged to master on next release). Creating a mixed solution that would animate by default and temporarily stop animating when the results are glitchy would add code complexity for very little benefit.
