### ISSUE TITLE
Improved control of popupview dimensions

### ISSUE THREAD

**Issue by koenvanderdrift** [alskipp/ASValueTrackingSlider#28]
First of all, thank you very much for sharing this class! I've been looking for something like this for a while, but all solutions I came across were pretty outdated.

Anyway, I'm using a pretty small font (size 12) for the text in the popUpView, and the relative size IMO of the popUpView is too big for that. I was able to tweak it by decreasing the values of `ARROW_LENGTH` and `MIN_POPUPVIEW_HEIGHT`, and it looks much better proportionally. Is this maybe something that could be built in the class, eg by making those constants a property, or size them based on the font size?

**Comment by alskipp** [comment]
Thanks to a contribution by @vince4, this issue should be solved. It is now possible to set the following property `CGFloat popUpViewWidthPaddingFactor`.

For example: a value of 2.0 would make the popUpView twice as wide as the width of the text.

The changes are merged into master, but haven't been updated on CocoaPods yet.
