### ISSUE TITLE
Missing the file “ValueTrackingSliderTests-Info.plist”

### ISSUE THREAD

**Issue by BanditsBacon** [alskipp/ASValueTrackingSlider#29]
If i try ``` pod try ASValueTrackingSlider``` and try to build the xcode project i run in this failure. 
```error: could not read data from '/tmp/CocoaPods/Try/ASValueTrackingSlider/Example/ValueTrackingSliderTests/ValueTrackingSliderTests-Info.plist': The file “ValueTrackingSliderTests-Info.plist” couldn’t be opened because there is no such file.````
The same when i download the Project as zip and try to build the example project.

Cheers

**Comment by colasjojo** [comment]
I have the same issue when downloading the `.zip` folder.

**Comment by alskipp** [comment]
With the latest release this annoying issue should have vanished.
