### ISSUE TITLE
Does this support ranges to display multiple sliders?

### ISSUE THREAD

**Issue by azamsharp** [alskipp/ASValueTrackingSlider#32]
Does this support ranges to display multiple sliders? 

Really awesome work!

**Comment by ericgross** [comment]
:+1:

**Comment by alskipp** [comment]
Apologies for the late response. Alas, ranges are not supported. It would add significant complexity and confusion to both the public API and the implementation to support both a normal value slider and a range version in one control.

The only suggestion I can make is that you could find an open source range slider and retrofit the `ASValuePopUpView` on top of it. One complication I can envisage is that when the two sliders are close together, extra logic will need to be provided to prevent the popUpViews from overlapping.

Good luck in your mission and please extract as much code from this project as needed if it will be of benefit.

All the best,
Al
