### ISSUE TITLE
how to adjust animation speed and how to always show values

### ISSUE THREAD

**Issue by wangbourne** [alskipp/ASValueTrackingSlider#34]
As titled, 
How to adjust animation speed and how to always show values?

Thanks

**Comment by alskipp** [comment]
To always show the popUpView you just need to call `showPopUpViewAnimated:NO` in `ViewDidLoad`.

I'm not certain what you are referring to regarding the animation speed? If you mean the color animation as you drag the slider, then you can specify the positions as follows:

```objective-c
[slider setPopUpViewAnimatedColors:@[[UIColor purpleColor], [UIColor greenColor], [UIColor orangeColor]]
                     withPositions:@[@0.0, @0.1, @1.0]];
```
The popUpView will be purple at the start, then green at 10%, then gradually become orange at 100%.
