### ISSUE TITLE
Cannot adjust popup size

### ISSUE THREAD

**Issue by LeeroyDing** [alskipp/ASValueTrackingSlider#35]
The slider popup looks weird with custom fonts (e.g. small Roboto fonts). There should be a way (without modifying the source) to specify the size of the popup view, maybe by allowing clients to customize width/height padding factors.

**Comment by LeeroyDing** [comment]
never mind

**Comment by alskipp** [comment]
I guess you either stopped using Roboto ; ) or found…

```obj-c
// width padding factor of the popUpView, default is 1.15
@property (nonatomic) CGFloat popUpViewWidthPaddingFactor;
// height padding factor of the popUpView, default is 1.1
@property (nonatomic) CGFloat popUpViewHeightPaddingFactor;
```
I do need to update the README and the CocoaPods version, as these are recent additions.

**Comment by LeeroyDing** [comment]
I was using this library ~1mo ago and found this issue. The project ended and I was trying to implement this, until I found it myself :|
