### ISSUE TITLE
Is there a way to show live values without showing popup?

### ISSUE THREAD

**Issue by hagile** [alskipp/ASValueTrackingSlider#39]
As title say, is this possible?

**Comment by alskipp** [comment]
I don't understand the question. Where would the live values be displayed?

**Comment by ruchiragile** [comment]
it should be display without having a popup?

**Comment by ruchiragile** [comment]
it should be display without having a popup?

**Comment by hagile** [comment]
I don't want to show live value inside a popup instead a lable, may be?

**Comment by hagile** [comment]
btw, I've decided to skip ASValueTrackingSlider and stick to `UISlider` – I've implemented that thing on my own :+1:
