### ISSUE TITLE
Rotating the uislider makes the popupview rotate too

### ISSUE THREAD

**Issue by Sneakr** [alskipp/ASValueTrackingSlider#43]
Hi and Thanks for a great addon! 

When i use CGAffineTransformMakeRotation(-M_PI * 90 / 180.0f)

on my uislider to make it rotate 90* standing up, the popupvalueview also rotates with the slider, is there anyway to prevent this ?

**Comment by alskipp** [comment]
The component wasn't designed with this use case in mind. My hacky suggestion is to set the opposite transform on the `popUpView` in the `setUp` method in `ASValueTrackingSlider.m`. If you ensure the transform occurs from the bottom-center of the `popUpView`, it should have the desired effect.

**Comment by Sneakr** [comment]
Thanks! I will try it out :+1:
