### ISSUE TITLE
Updated Cocoapod soon?

### ISSUE THREAD

**Issue by rbaumbach** [alskipp/ASValueTrackingSlider#45]
Looking at ASValuePopUpView.h on master you have the a property that I need to update the arrow length:

```objective-c
@interface ASValuePopUpView : UIView

@property (nonatomic) CGFloat arrowLength;
```

However, using the latest Cocoapod, 0.10.1 (which points to tag 0.10.1), this property doesn't exist.  Is there a plan to roll out this change in an updated Cocoapod soon?

Thanks!

**Comment by alskipp** [comment]
Thanks for the reminder! This really should have happened a while ago - whoops! My focus has been on various Swift projects, so venturing back to Obj-C tends to feel a little painful ; )
As a temporary workaround you could specify the commit in your podfile. See my response in #46. I'll get this sorted ASAP.

**Comment by rbaumbach** [comment]
Thanks, I have been using the latest commit in my podfile for now to get the working.  This issue was opened just to see if you plan on updating it soon =)

Thanks!

**Comment by alskipp** [comment]
Finally got around to releasing the new version : )
