### ISSUE TITLE
while ASProgressPopUpView and ASValueTrackingSlider in the some work

### ISSUE THREAD

**Issue by bingxue314159** [alskipp/ASValueTrackingSlider#46]
while ASProgressPopUpView and ASValueTrackingSlider in the some work,then wrong:
const float ARROW_LENGTH = 8.0;
const float POPUPVIEW_WIDTH_PAD = 1.15;
const float POPUPVIEW_HEIGHT_PAD = 1.1;
NSString *const FillColorAnimation = @"fillColor";

**Comment by alskipp** [comment]
As a temporary workaround could I suggest you specify in your podfile a specific commit. The following should work:

```
pod 'ASValueTrackingSlider', :git => 'https://github.com/alskipp/ASValueTrackingSlider', :commit => '7a6e5290c9e9344773c4'
```

I need to update the pod with a new version (see #45). I'll try and get that done today, or tomorrow.

**Comment by alskipp** [comment]
Latest pod release (0.11.2) should fix the this.
