### ISSUE TITLE
speechless problem

### ISSUE THREAD

**Issue by codesourse** [alskipp/ASValueTrackingSlider#48]
duplicate symbol _FillColorAnimation in:
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASProgressPopUpView.a(ASPopUpView.o)
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASValueTrackingSlider.a(ASValuePopUpView.o)
duplicate symbol _ARROW_LENGTH in:
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASProgressPopUpView.a(ASPopUpView.o)
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASValueTrackingSlider.a(ASValuePopUpView.o)
duplicate symbol _POPUPVIEW_HEIGHT_PAD in:
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASProgressPopUpView.a(ASPopUpView.o)
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASValueTrackingSlider.a(ASValuePopUpView.o)
duplicate symbol _POPUPVIEW_WIDTH_PAD in:
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASProgressPopUpView.a(ASPopUpView.o)
    /Users/kjx/Library/Developer/Xcode/DerivedData/XHEnglishBrushStudent-cxzudhmcyvisjbazxhbeptwqyszn/Build/Products/Debug-iphonesimulator/libASValueTrackingSlider.a(ASValuePopUpView.o)
ld: 4 duplicate symbols for architecture x86_64

**Comment by alskipp** [comment]
Looks like clearing Xcode's `DerivedData` folder should fix this.
