### ISSUE TITLE
Compiler warning on Xcode 8 GM + fix

### ISSUE THREAD

**Issue by koenvanderdrift** [alskipp/ASValueTrackingSlider#54]
I got the following compiler warning on Xcode 8:

`/ASValueTrackingSlider/ASValueTrackingSlider/ASValuePopUpView.m:157:24: Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'ASValuePopUpView *const __strong'`

I fixed it as follows:

`@interface ASValuePopUpView : UIView <CAAnimationDelegate>`

Tried to push it using git, but kept getting permission errors, so I am posting it here.

Cheers

**Comment by alskipp** [comment]
Thanks for flagging the issue. The latest release (0.12.1) should resolve this.
