### ISSUE TITLE
Feature request: vertical slider?

### ISSUE THREAD

**Issue by amitMist** [alskipp/ASValueTrackingSlider#58]
Is there any plan for this? This slider is awesome. :)

**Comment by alskipp** [comment]
Thanks for the kind words! 

I think to get a vertical slider working well would require a significant amount of work, so it's not something which is currently planned. In a vertical configuration the popup view would probably need to pop from the either the left or right of the slider track and the shape would need to adapt to this new layout.

There's a hacky suggestion to get it basically working (the popup will overlay the slider track, which may or may not be ideal for your needs?): https://github.com/alskipp/ASValueTrackingSlider/issues/43
